project1/wiki/encyclopedia/urls.py
from django.urls import path
from . import views

app_name = "encyclopedia"

urlpatterns = [
    path("", views.index, name="index"),
    path("<str:title>", views.entry, name="entry"),
    path("search/", views.search, name="search"),
    path("create/", views.create, name="create"),
    path("edit/<str:title>", views.edit, name="edit"),
    path("random/", views.random_page, name="random"),
]

project1/wiki/wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include("encyclopedia.urls"))
]

project1/wiki/encyclopedia/models.py
from django.db import models

# Create your models here.

project1/wiki/encyclopedia/views.py
from django.http import HttpResponse
from markdown2 import Markdown
from django.shortcuts import redirect, render
import random
from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {"entries": util.list_entries()})


def entry(request, title):
    markdowner = Markdown()
    content = util.get_entry(title)
    if content is None:
        return render(request, "encyclopedia/not_found.html")
    content_convrted = markdowner.convert(content)
    return render(
        request,
        "encyclopedia/entry.html",
        {"title": title, "content": content_convrted},
    )


def search(request):
    query = request.GET.get("q")

    if query:
        entry_content = util.get_entry(query)

        if entry_content:
            return redirect("encyclopedia:entry", title=query)
        else:
            entries = [
                title for title in util.list_entries() if query.lower() in title.lower()
            ]

            return render(
                request,
                "encyclopedia/search_results.html",
                {"entries": entries, "query": query},
            )
    else:
        return render(
            request,
            "encyclopedia/search_results.html",
            {
                "entries": [],
                "query": query,
                "error_message": "Please enter a search query in the search box.",
            },
        )


def create(request):
    if request.method == "POST":
        title = request.POST.get("title")
        content = request.POST.get("content")
        if util.get_entry(title):
            return render(
                request,
                "encyclopedia/create.html",
                {
                    "error_message": "An encyclopedia entry with this title already exists. Please choose a different title.",
                    "title": title,
                    "content": content,
                },
            )
        else:
            util.save_entry(title, content)
            return redirect("encyclopedia:entry", title=title)

    return render(request, "encyclopedia/create.html")


def edit(request, title):
    if request.method == "POST":
        content = request.POST.get("content")

        util.save_entry(title, content)
        return redirect(
            "encyclopedia:entry", title=title
        )

    entry_content = util.get_entry(title)
    if entry_content is None:
        return render(request, "encyclopedia/edit.html", {"error_message": "Entry not_found for editing."})

    return render(
        request,
        "encyclopedia/edit.html",
        {
            "title": title,
            "content": entry_content,
        },
    )


def random_page(request):
    entries = util.list_entries()  # Get a list of all entry titles
    random_entry_title = random.choice(entries)  # Choose a random title
    return redirect("encyclopedia:entry", title=random_entry_title)  # Redirect

project1/wiki/encyclopedia/templates/encyclopedia/create.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Create New Page
{% endblock title %}
{% block body %}
    <h1>Create a New Encyclopedia Entry</h1>
    {% if error_message %}<div class="error">{{ error_message }}</div>{% endif %}
    <form action="{% url 'encyclopedia:create' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Title:</label>
            <input type="text"
                   class="form-control"
                   id="title"
                   name="title"
                   required
                   value="{{ title|default:'' }}">
        </div>
        <div class="form-group">
            <label for="content">Content (Markdown):</label>
            <textarea class="form-control" id="content" name="content" rows="10" required>{{ content|default:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">Save Page</button>
    </form>
{% endblock body %}

project1/wiki/encyclopedia/templates/encyclopedia/edit.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    Encyclopedia/Edit/{{ title }}
{% endblock title %}
{% block body %}
    <h1>Edit Page: "{{ title }}"</h1>
    {% if error_message %}
        <div class="error">
            <h3>{{ error_message }}</h3>
        </div>
    {% else %}
        <form action="{% url 'encyclopedia:edit' title=title %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="content">Content (Markdown):</label>
                <textarea class="form-control" id="content" name="content" rows="15" required>{{ content }}</textarea>
                {# No Title field in edit form for now #}
            </div>
            <button type="submit" class="btn btn-primary">Save Changes</button>
        </form>
    {% endif %}
{% endblock body %}

project1/wiki/encyclopedia/templates/encyclopedia/entry.html
{% extends "encyclopedia/layout.html" %}
{% block title %}Encyclopedia/{{ title }}{% endblock %}
{% block body %}
{{ content | safe }}
    <hr>
    <p>
        <a href="{% url 'encyclopedia:edit' title=title %}">Edit this page</a>
    </p>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}
{% block title %}Encyclopedia{% endblock %}
{% block body %}
    <h1>All Pages</h1>
    <ul>
        {% for entry in entries %}
            <li>
                <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>
            {% block title %}{% endblock %}
        </title>
        <link rel="stylesheet"
              href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
              integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
              crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{% url 'encyclopedia:search' %}" method="get">
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div>
                    <a href="{% url 'encyclopedia:index' %}">Home</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:create' %}">Create New Page</a>
                </div>
                <div>
                    <a href="{% url 'encyclopedia:random' %}">Random Page</a>
                </div>
                {% block nav %}{% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}{% endblock %}
            </div>
        </div>
    </body>
</html>

project1/wiki/encyclopedia/templates/encyclopedia/not_found.html
{% extends "encyclopedia/layout.html" %}

{% block body %}  
  <h1>NOT FOUND</h1>
{% endblock %}

project1/wiki/encyclopedia/templates/encyclopedia/search_results.html
{% extends "encyclopedia/layout.html" %}
{% block title %}
    "Encyclopedia/{{ query }}"
{% endblock title %}
{% block body %}
    {% if error_message %}
        <div class="error">
            <h1>{{ error_message }}</h1>
        </div>
    {% else %}
        <h1>Search Results for "{{ query }}"</h1>
        <ul>
            {% for entry in entries %}
                <li>
                    <a href="{% url 'encyclopedia:entry' entry %}">{{ entry }}</a>
                </li>
            {% empty %}
                <li>No entries found that match your search query.</li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock body %}